Imports Microsoft.EntityFrameworkCore
Imports WecErp.Domain

Namespace WecErp.Infrastructure
    Public Class ErpDbContext
        Inherits DbContext

        Public Sub New(options As DbContextOptions(Of ErpDbContext))
            MyBase.New(options)
        End Sub

        Public Property Items As DbSet(Of Item)
        Public Property Customers As DbSet(Of Customer)
        Public Property Suppliers As DbSet(Of Supplier)
        Public Property Quotations As DbSet(Of Quotation)
        Public Property QuotationLines As DbSet(Of QuotationLine)
        Public Property SalesOrders As DbSet(Of SalesOrder)
        Public Property SalesOrderLines As DbSet(Of SalesOrderLine)
        Public Property Resources As DbSet(Of Resource)
        Public Property Bookings As DbSet(Of Booking)
        Public Property Warehouses As DbSet(Of Warehouse)
        Public Property InventoryMovements As DbSet(Of InventoryMovement)
        Public Property PurchaseOrders As DbSet(Of PurchaseOrder)
        Public Property PurchaseOrderLines As DbSet(Of PurchaseOrderLine)
        Public Property PurchaseReceipts As DbSet(Of PurchaseReceipt)
        Public Property PurchaseReceiptLines As DbSet(Of PurchaseReceiptLine)

        Protected Overrides Sub OnModelCreating(modelBuilder As ModelBuilder)
            MyBase.OnModelCreating(modelBuilder)

            Dim item = modelBuilder.Entity(Of Item)()
            item.ToTable("Items")
            item.HasKey(Function(x) x.Id)
            item.Property(Function(x) x.Sku).HasMaxLength(100).IsRequired()
            item.Property(Function(x) x.Name).HasMaxLength(300).IsRequired()
            item.HasIndex(Function(x) x.Sku).IsUnique()
            item.Property(Function(x) x.Type).IsRequired()
            item.Property(Function(x) x.IsActive).IsRequired()

            Dim customer = modelBuilder.Entity(Of Customer)()
            customer.ToTable("Customers")
            customer.HasKey(Function(x) x.Id)
            customer.Property(Function(x) x.Code).HasMaxLength(50).IsRequired()
            customer.Property(Function(x) x.Name).HasMaxLength(300).IsRequired()
            customer.Property(Function(x) x.Phone).HasMaxLength(50)
            customer.Property(Function(x) x.Email).HasMaxLength(320)
            customer.Property(Function(x) x.TaxNumber).HasMaxLength(50)
            customer.Property(Function(x) x.IsActive).IsRequired()
            customer.Property(Function(x) x.CreatedUtc).IsRequired()
            customer.HasIndex(Function(x) x.Code).IsUnique()

            Dim supplier = modelBuilder.Entity(Of Supplier)()
            supplier.ToTable("Suppliers")
            supplier.HasKey(Function(x) x.Id)
            supplier.Property(Function(x) x.Code).HasMaxLength(50).IsRequired()
            supplier.Property(Function(x) x.Name).HasMaxLength(300).IsRequired()
            supplier.Property(Function(x) x.Phone).HasMaxLength(50).IsRequired()
            supplier.Property(Function(x) x.Email).HasMaxLength(320).IsRequired()
            supplier.Property(Function(x) x.TaxNumber).HasMaxLength(50).IsRequired()
            supplier.Property(Function(x) x.IsActive).IsRequired()
            supplier.Property(Function(x) x.CreatedUtc).IsRequired()
            supplier.HasIndex(Function(x) x.Code).IsUnique()

            Dim quotation = modelBuilder.Entity(Of Quotation)()
            quotation.ToTable("Quotations")
            quotation.HasKey(Function(x) x.Id)
            quotation.Property(Function(x) x.Number).HasMaxLength(60).IsRequired()
            quotation.HasIndex(Function(x) x.Number).IsUnique()
            quotation.Property(Function(x) x.CurrencyCode).HasMaxLength(3).IsRequired()
            quotation.Property(Function(x) x.Subtotal).HasPrecision(19, 4)
            quotation.Property(Function(x) x.DiscountAmount).HasPrecision(19, 4)
            quotation.Property(Function(x) x.TaxAmount).HasPrecision(19, 4)
            quotation.Property(Function(x) x.Total).HasPrecision(19, 4)
            quotation.HasOne(Of Customer)().WithMany().HasForeignKey(Function(x) x.CustomerId).OnDelete(DeleteBehavior.Restrict)
            quotation.HasMany(Function(x) x.Lines).WithOne().HasForeignKey(Function(x) x.QuotationId).OnDelete(DeleteBehavior.Cascade)

            Dim quotationLine = modelBuilder.Entity(Of QuotationLine)()
            quotationLine.ToTable("QuotationLines")
            quotationLine.HasKey(Function(x) x.Id)
            quotationLine.Property(Function(x) x.Description).HasMaxLength(500).IsRequired()
            quotationLine.Property(Function(x) x.Quantity).HasPrecision(19, 4)
            quotationLine.Property(Function(x) x.UnitPrice).HasPrecision(19, 4)
            quotationLine.Property(Function(x) x.DiscountPercent).HasPrecision(9, 4)
            quotationLine.Property(Function(x) x.TaxPercent).HasPrecision(9, 4)
            quotationLine.Property(Function(x) x.LineSubtotal).HasPrecision(19, 4)
            quotationLine.Property(Function(x) x.LineDiscount).HasPrecision(19, 4)
            quotationLine.Property(Function(x) x.LineTax).HasPrecision(19, 4)
            quotationLine.Property(Function(x) x.LineTotal).HasPrecision(19, 4)
            quotationLine.HasOne(Of Item)().WithMany().HasForeignKey(Function(x) x.ItemId).OnDelete(DeleteBehavior.Restrict)

            Dim salesOrder = modelBuilder.Entity(Of SalesOrder)()
            salesOrder.ToTable("SalesOrders")
            salesOrder.HasKey(Function(x) x.Id)
            salesOrder.Property(Function(x) x.Number).HasMaxLength(60).IsRequired()
            salesOrder.HasIndex(Function(x) x.Number).IsUnique()
            salesOrder.HasIndex(Function(x) x.SourceQuotationId).IsUnique().HasFilter("[SourceQuotationId] IS NOT NULL")
            salesOrder.Property(Function(x) x.CurrencyCode).HasMaxLength(3).IsRequired()
            salesOrder.Property(Function(x) x.Subtotal).HasPrecision(19, 4)
            salesOrder.Property(Function(x) x.DiscountAmount).HasPrecision(19, 4)
            salesOrder.Property(Function(x) x.TaxAmount).HasPrecision(19, 4)
            salesOrder.Property(Function(x) x.Total).HasPrecision(19, 4)
            salesOrder.Property(Function(x) x.CreatedUtc).IsRequired()
            salesOrder.HasOne(Of Customer)().WithMany().HasForeignKey(Function(x) x.CustomerId).OnDelete(DeleteBehavior.Restrict)
            salesOrder.HasOne(Of Quotation)().WithMany().HasForeignKey(Function(x) x.SourceQuotationId).OnDelete(DeleteBehavior.Restrict)
            salesOrder.HasMany(Function(x) x.Lines).WithOne().HasForeignKey(Function(x) x.SalesOrderId).OnDelete(DeleteBehavior.Cascade)

            Dim salesOrderLine = modelBuilder.Entity(Of SalesOrderLine)()
            salesOrderLine.ToTable("SalesOrderLines")
            salesOrderLine.HasKey(Function(x) x.Id)
            salesOrderLine.Property(Function(x) x.Description).HasMaxLength(500).IsRequired()
            salesOrderLine.Property(Function(x) x.Quantity).HasPrecision(19, 4)
            salesOrderLine.Property(Function(x) x.UnitPrice).HasPrecision(19, 4)
            salesOrderLine.Property(Function(x) x.DiscountPercent).HasPrecision(9, 4)
            salesOrderLine.Property(Function(x) x.TaxPercent).HasPrecision(9, 4)
            salesOrderLine.Property(Function(x) x.LineSubtotal).HasPrecision(19, 4)
            salesOrderLine.Property(Function(x) x.LineDiscount).HasPrecision(19, 4)
            salesOrderLine.Property(Function(x) x.LineTax).HasPrecision(19, 4)
            salesOrderLine.Property(Function(x) x.LineTotal).HasPrecision(19, 4)
            salesOrderLine.HasOne(Of Item)().WithMany().HasForeignKey(Function(x) x.ItemId).OnDelete(DeleteBehavior.Restrict)

            Dim resource = modelBuilder.Entity(Of Resource)()
            resource.ToTable("Resources")
            resource.HasKey(Function(x) x.Id)
            resource.Property(Function(x) x.Code).HasMaxLength(50).IsRequired()
            resource.Property(Function(x) x.Name).HasMaxLength(200).IsRequired()
            resource.Property(Function(x) x.Type).IsRequired()
            resource.Property(Function(x) x.IsActive).IsRequired()
            resource.HasIndex(Function(x) x.Code).IsUnique()

            Dim booking = modelBuilder.Entity(Of Booking)()
            booking.ToTable("Bookings")
            booking.HasKey(Function(x) x.Id)
            booking.Property(Function(x) x.Number).HasMaxLength(60).IsRequired()
            booking.HasIndex(Function(x) x.Number).IsUnique()
            booking.Property(Function(x) x.StartsUtc).IsRequired()
            booking.Property(Function(x) x.EndsUtc).IsRequired()
            booking.Property(Function(x) x.Notes).IsRequired()
            booking.Property(Function(x) x.CreatedUtc).IsRequired()
            booking.HasIndex(Function(x) New With {x.ResourceId, x.StartsUtc, x.EndsUtc})
            booking.HasOne(Of Customer)().WithMany().HasForeignKey(Function(x) x.CustomerId).OnDelete(DeleteBehavior.Restrict)
            booking.HasOne(Of Item)().WithMany().HasForeignKey(Function(x) x.ItemId).OnDelete(DeleteBehavior.Restrict)
            booking.HasOne(Of Resource)().WithMany().HasForeignKey(Function(x) x.ResourceId).OnDelete(DeleteBehavior.Restrict)

            Dim warehouse = modelBuilder.Entity(Of Warehouse)()
            warehouse.ToTable("Warehouses")
            warehouse.HasKey(Function(x) x.Id)
            warehouse.Property(Function(x) x.Code).HasMaxLength(50).IsRequired()
            warehouse.Property(Function(x) x.Name).HasMaxLength(200).IsRequired()
            warehouse.Property(Function(x) x.IsActive).IsRequired()
            warehouse.Property(Function(x) x.CreatedUtc).IsRequired()
            warehouse.HasIndex(Function(x) x.Code).IsUnique()

            Dim purchaseOrder = modelBuilder.Entity(Of PurchaseOrder)()
            purchaseOrder.ToTable("PurchaseOrders")
            purchaseOrder.HasKey(Function(x) x.Id)
            purchaseOrder.Property(Function(x) x.Number).HasMaxLength(60).IsRequired()
            purchaseOrder.HasIndex(Function(x) x.Number).IsUnique()
            purchaseOrder.Property(Function(x) x.CurrencyCode).HasMaxLength(3).IsRequired()
            purchaseOrder.Property(Function(x) x.Subtotal).HasPrecision(19, 4)
            purchaseOrder.Property(Function(x) x.TaxAmount).HasPrecision(19, 4)
            purchaseOrder.Property(Function(x) x.Total).HasPrecision(19, 4)
            purchaseOrder.Property(Function(x) x.Notes).HasMaxLength(500).IsRequired()
            purchaseOrder.Property(Function(x) x.CreatedUtc).IsRequired()
            purchaseOrder.HasOne(Of Supplier)().WithMany().HasForeignKey(Function(x) x.SupplierId).OnDelete(DeleteBehavior.Restrict)
            purchaseOrder.HasMany(Function(x) x.Lines).WithOne().HasForeignKey(Function(x) x.PurchaseOrderId).OnDelete(DeleteBehavior.Cascade)

            Dim purchaseOrderLine = modelBuilder.Entity(Of PurchaseOrderLine)()
            purchaseOrderLine.ToTable("PurchaseOrderLines")
            purchaseOrderLine.HasKey(Function(x) x.Id)
            purchaseOrderLine.Property(Function(x) x.Description).HasMaxLength(500).IsRequired()
            purchaseOrderLine.Property(Function(x) x.OrderedQuantity).HasPrecision(19, 4)
            purchaseOrderLine.Property(Function(x) x.UnitCost).HasPrecision(19, 4)
            purchaseOrderLine.Property(Function(x) x.TaxPercent).HasPrecision(9, 4)
            purchaseOrderLine.Property(Function(x) x.LineSubtotal).HasPrecision(19, 4)
            purchaseOrderLine.Property(Function(x) x.LineTax).HasPrecision(19, 4)
            purchaseOrderLine.Property(Function(x) x.LineTotal).HasPrecision(19, 4)
            purchaseOrderLine.HasOne(Of Item)().WithMany().HasForeignKey(Function(x) x.ItemId).OnDelete(DeleteBehavior.Restrict)

            Dim purchaseReceipt = modelBuilder.Entity(Of PurchaseReceipt)()
            purchaseReceipt.ToTable("PurchaseReceipts")
            purchaseReceipt.HasKey(Function(x) x.Id)
            purchaseReceipt.Property(Function(x) x.Number).HasMaxLength(60).IsRequired()
            purchaseReceipt.HasIndex(Function(x) x.Number).IsUnique()
            purchaseReceipt.Property(Function(x) x.CreatedUtc).IsRequired()
            purchaseReceipt.HasOne(Of PurchaseOrder)().WithMany().HasForeignKey(Function(x) x.PurchaseOrderId).OnDelete(DeleteBehavior.Restrict)
            purchaseReceipt.HasOne(Of Warehouse)().WithMany().HasForeignKey(Function(x) x.WarehouseId).OnDelete(DeleteBehavior.Restrict)
            purchaseReceipt.HasMany(Function(x) x.Lines).WithOne().HasForeignKey(Function(x) x.PurchaseReceiptId).OnDelete(DeleteBehavior.Cascade)

            Dim purchaseReceiptLine = modelBuilder.Entity(Of PurchaseReceiptLine)()
            purchaseReceiptLine.ToTable("PurchaseReceiptLines")
            purchaseReceiptLine.HasKey(Function(x) x.Id)
            purchaseReceiptLine.Property(Function(x) x.Quantity).HasPrecision(19, 4)
            purchaseReceiptLine.HasOne(Of PurchaseOrderLine)().WithMany().HasForeignKey(Function(x) x.PurchaseOrderLineId).OnDelete(DeleteBehavior.Restrict)
            purchaseReceiptLine.HasOne(Of Item)().WithMany().HasForeignKey(Function(x) x.ItemId).OnDelete(DeleteBehavior.Restrict)

            Dim movement = modelBuilder.Entity(Of InventoryMovement)()
            movement.ToTable("InventoryMovements")
            movement.HasKey(Function(x) x.Id)
            movement.Property(Function(x) x.Type).IsRequired()
            movement.Property(Function(x) x.Quantity).HasPrecision(19, 4)
            movement.Property(Function(x) x.ReferenceType).HasMaxLength(100).IsRequired()
            movement.Property(Function(x) x.Notes).HasMaxLength(500).IsRequired()
            movement.Property(Function(x) x.CreatedUtc).IsRequired()
            movement.HasIndex(Function(x) New With {x.ItemId, x.WarehouseId, x.CreatedUtc})
            movement.HasIndex(Function(x) New With {x.ReferenceType, x.ReferenceId})
            movement.HasOne(Of Item)().WithMany().HasForeignKey(Function(x) x.ItemId).OnDelete(DeleteBehavior.Restrict)
            movement.HasOne(Of Warehouse)().WithMany().HasForeignKey(Function(x) x.WarehouseId).OnDelete(DeleteBehavior.Restrict)
        End Sub
    End Class
End Namespace
